# Generated by Django 4.0.4 on 2022-07-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='facebook_link',
            new_name='linkedin_link',
        ),
    ]
