# Generated by Django 4.0 on 2022-10-29 16:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_facebook_link_team_linkedin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
