# Generated by Django 4.0.4 on 2022-10-14 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_country_remove_car_no_of_answers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='interior',
            new_name='interior_color',
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000)]),
        ),
    ]
