# Generated by Django 4.0.4 on 2022-10-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_interior_car_interior_color_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chhattisgarh'), ('GOA', 'Goa'), ('GJ', 'Gujarat'), ('HAR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JD', 'Jharkhand'), ('KAR', 'Karnataka'), ('KER', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MNP', 'Manipur'), ('MEG', 'Meghalaya'), ('MZ', 'Mizoram'), ('NGL', 'Nagaland'), ('ODI', 'Odisha'), ('PUN', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UT', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=100),
        ),
    ]
